version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - "./elasticsearch/data:/usr/share/elasticsearch/data"
    networks:
      - elastic-stack

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    ports:
      - "5601:5601"
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_URL: http://localhost:9200
    networks:
      - elastic-stack

  logstach:
    image: docker.elastic.co/logstash/logstash:7.3.1
    volumes:
      - "./pipeline/:/usr/share/logstash/pipeline/"
    networks:
      - elastic-stack

networks:
    elastic-stack: